version: '2.3'
services:
  nginx:
    depends_on:
      - annotation-tool
    image: nginx:1.18
    volumes:
      - "./nginx_config/my_site:/etc/nginx/conf.d/default.conf"
      - "./authentication/.htpasswd:/etc/apache2/.htpasswd"
      - "./certs/star_insight-centre_org.pem:/etc/nginx/certs/star_insight-centre_org.pem"
      - "./certs/insight-centre-org.key:/etc/nginx/certs/insight-centre-org.key"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  annotation-tool:
    image: registry.insight-centre.org/annsou/annotation-tool:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - "./static/videos:/app/static/videos"
      - "./video_annotation.db:/app/video_annotation.db"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    restart: unless-stopped
